(() => {
  const $ = id => document.getElementById(id);
  const db = window.rentCarSupabase;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money = value => window.formatMGA ? window.formatMGA(value) : `${Number(value || 0).toLocaleString('fr-FR')} Ar`;
  const permitLabels = {A:'Moto (A)', B:'Voiture (B)', C:'Poids lourd (C)'};
  const availabilityLabels = {available:'Disponible', by_booking:'Sur réservation', unavailable:'Indisponible'};
  const rateIds = ['city-daily','city-24h','province-daily','delivery','recovery'];

  function formPayload() {
    const rates = Object.fromEntries(rateIds.map(key => [key, Number($(`driver-${key}`)?.value || 0)]));
    if (Object.values(rates).some(value => value < 20000 || value > 50000)) throw new Error('Les tarifs chauffeur doivent être compris entre 20 000 et 50 000 Ar.');
    return {name:$('driver-name').value.trim(), photo_url:$('driver-photo').value.trim() || null, phone:$('driver-phone').value.trim() || null, whatsapp:$('driver-whatsapp').value.trim() || null, permits:['A','B','C'].filter(code => $(`driver-permit-${code}`)?.checked), city_daily_rate:rates['city-daily'], city_24h_rate:rates['city-24h'], province_daily_rate:rates['province-daily'], delivery_rate:rates.delivery, recovery_rate:rates.recovery, lodging_included:$('driver-lodging').value === 'included', meals_included:$('driver-meals').value === 'included', availability:$('driver-availability').value, description:$('driver-description').value.trim() || null, languages:$('driver-languages').value.trim() || null, experience_years:Number($('driver-experience').value || 0) || null, active:true};
  }
  function resetForm() { $('driver-form')?.reset(); $('driver-id').value=''; $('driver-city-daily').value=30000; $('driver-city-24h').value=40000; $('driver-province-daily').value=50000; $('driver-delivery').value=20000; $('driver-recovery').value=20000; $('driver-form').classList.remove('hidden'); }
  async function loadDrivers() { const {data,error}=await db.from('chauffeurs').select('*').order('created_at',{ascending:false}); if (error) { $('drivers-table').innerHTML=`<div class="notice">Impossible de charger les chauffeurs : ${esc(error.message)}</div>`; return []; } renderDrivers(data || []); return data || []; }
  function renderDrivers(rows) { $('drivers-table').innerHTML = rows.map(d => `<div class="card driver-admin-card"><div class="section-head"><div><strong>${esc(d.name)}</strong><br><small>${esc((d.permits||[]).map(p => permitLabels[p] || p).join(' · ') || 'Permis non renseigné')} · ${esc(availabilityLabels[d.availability] || d.availability)}</small></div><div class="actions"><button class="btn outline" onclick="window.editDriver('${d.id}')">Modifier</button><button class="btn ${d.active ? 'danger':'primary'}" onclick="window.toggleDriver('${d.id}',${!d.active})">${d.active?'Désactiver':'Activer'}</button></div></div><div class="driver-admin-rates">Ville : ${money(d.city_daily_rate)} / jour · Ville 24 h : ${money(d.city_24h_rate)} · Province : ${money(d.province_daily_rate)} / jour · Livraison : ${money(d.delivery_rate)} · Récupération : ${money(d.recovery_rate)}<br>Hébergement : ${d.lodging_included?'inclus':'non inclus'} · Repas : ${d.meals_included?'inclus':'non inclus'}</div></div>`).join('') || '<div class="empty">Aucun chauffeur enregistré.</div>'; }
  async function editDriver(id) { const {data,error}=await db.from('chauffeurs').select('*').eq('id',id).single(); if(error || !data) return alert(error?.message || 'Chauffeur introuvable.'); $('driver-id').value=data.id; $('driver-name').value=data.name||''; $('driver-photo').value=data.photo_url||''; $('driver-phone').value=data.phone||''; $('driver-whatsapp').value=data.whatsapp||''; ['A','B','C'].forEach(p => $(`driver-permit-${p}`).checked=(data.permits||[]).includes(p)); $('driver-city-daily').value=data.city_daily_rate; $('driver-city-24h').value=data.city_24h_rate; $('driver-province-daily').value=data.province_daily_rate; $('driver-delivery').value=data.delivery_rate; $('driver-recovery').value=data.recovery_rate; $('driver-lodging').value=data.lodging_included?'included':'not_included'; $('driver-meals').value=data.meals_included?'included':'not_included'; $('driver-availability').value=data.availability||'available'; $('driver-description').value=data.description||''; $('driver-languages').value=data.languages||''; $('driver-experience').value=data.experience_years||''; $('driver-form').classList.remove('hidden'); $('driver-form').scrollIntoView({behavior:'smooth'}); }
  async function toggleDriver(id,active) { const {error}=await db.from('chauffeurs').update({active}).eq('id',id); if(error) alert(error.message); else loadDrivers(); }
  function renderPublicDrivers(rows) { const target=$('drivers-grid'); if(!target)return; target.innerHTML=rows.map(d=>`<article class="driver-card">${d.photo_url?`<img src="${esc(d.photo_url)}" alt="${esc(d.name)}" loading="lazy">`: '<div class="driver-photo-placeholder"><i class="fas fa-user-tie"></i></div>'}<div class="driver-card-body"><h3>${esc(d.name)}</h3><p>${esc(availabilityLabels[d.availability]||'Sur réservation')} · Permis ${esc((d.permits||[]).join(', ')||'—')}</p>${d.description?`<p>${esc(d.description)}</p>`:''}<dl><div><dt>Ville</dt><dd>${money(d.city_daily_rate)} / jour</dd></div><div><dt>Ville 24 h</dt><dd>${money(d.city_24h_rate)}</dd></div><div><dt>Province</dt><dd>${money(d.province_daily_rate)} / jour</dd></div><div><dt>Livraison</dt><dd>${money(d.delivery_rate)}</dd></div><div><dt>Récupération</dt><dd>${money(d.recovery_rate)}</dd></div></dl><p class="driver-conditions">Hébergement : <strong>${d.lodging_included?'inclus':'non inclus'}</strong> · Repas : <strong>${d.meals_included?'inclus':'non inclus'}</strong></p><div class="car-actions">${d.whatsapp?`<a class="btn btn-whatsapp" target="_blank" rel="noopener" href="https://wa.me/${encodeURIComponent(String(d.whatsapp).replace(/\D/g,''))}">WhatsApp</a>`:''}${d.phone?`<a class="btn btn-outline" href="tel:${encodeURIComponent(d.phone)}">Appeler</a>`:''}</div></div></article>`).join('') || '<p class="fleet-empty">Aucun chauffeur disponible pour le moment.</p>'; }
  document.addEventListener('DOMContentLoaded', async () => { const form=$('driver-form'); if(form) { $('driver-add')?.addEventListener('click',resetForm); form.addEventListener('submit',async e=>{e.preventDefault();let payload;try{payload=formPayload()}catch(error){alert(error.message);return}const id=$('driver-id').value;const result=id?await db.from('chauffeurs').update(payload).eq('id',id):await db.from('chauffeurs').insert(payload);if(result.error){alert(result.error.message);return}form.classList.add('hidden');await loadDrivers();}); await loadDrivers(); } if($('drivers-grid')) { const {data}=await db.from('chauffeurs').select('*').eq('active',true).neq('availability','unavailable').order('name'); renderPublicDrivers(data||[]); } });
  window.editDriver=editDriver; window.toggleDriver=toggleDriver;
})();
