(() => {
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const zoneLabel = zone => zone === 'under_150' ? 'Province jusqu’à 150 km de Tana' : zone === 'over_150' ? 'Province au-delà de 150 km de Tana' : 'Tana et environs';
  const findVehicle = id => {
    const groups = window.bookingFleets || window.publicCars || [];
    for (const item of groups) for (const v of (item.units || [item.vehicle || item])) if (v?.id === id) return v;
    return null;
  };
  const rateFor = (vehicle, zone) => {
    if (zone === 'city') return Number(vehicle.price_per_day || vehicle.price_12h || 0) || null;
    const mode = vehicle[`province_${zone}_mode`] || 'quote';
    return mode === 'price' && Number(vehicle[`province_${zone}_price`] || 0) > 0 ? Number(vehicle[`province_${zone}_price`]) : null;
  };
  function printQuote(q) {
    const total = q.total_amount ? formatMGA(q.total_amount) : 'Sur devis';
    const html = `<html><head><title>Devis ${esc(q.reference)}</title><style>body{font:14px Arial;line-height:1.5;padding:35px;max-width:820px;margin:auto;color:#0b1f33}h1{text-align:center;color:#0d5c8f}.box{border:1px solid #ccd5dd;border-radius:8px;padding:14px;margin:14px 0}.total{font-size:20px;font-weight:bold;color:#a7700d}.sign{display:flex;justify-content:space-between;margin-top:90px}</style></head><body><h1>Rent Car Service</h1><p>67 Ha Nord Ouest, Parking FJKM SALEMA<br>034 91 207 26</p><h2>DEVIS / FACTURE PRO FORMA</h2><p><strong>Référence :</strong> ${esc(q.reference)}<br><strong>Fait à Antananarivo, le :</strong> ${new Date().toLocaleDateString('fr-FR')}</p><div class="box"><strong>Client :</strong> ${esc(q.customer_name)} ${esc(q.customer_first_name)}<br><strong>WhatsApp :</strong> ${esc(q.whatsapp_phone)}<br><strong>Adresse :</strong> ${esc(q.customer_address)}</div><div class="box"><strong>Véhicule :</strong> ${esc(q.vehicle.name || q.vehicle.nom)}<br><strong>Période :</strong> ${esc(q.start_at)} → ${esc(q.end_at)}<br><strong>Zone :</strong> ${esc(zoneLabel(q.zone))}<br><strong>Durée :</strong> ${q.days} jour(s)}</div><p class="total">Total estimatif : ${total}</p><p>Après accord du client et validation par Rent Car Service, ce devis peut être converti en réservation et faire l’objet d’un contrat de location.</p><div class="sign"><span>CLIENT<br><br>Signature :</span><span>RENT CAR SERVICE<br><br>Signature :</span></div><script>window.print()<\/script></body></html>`;
    const win = window.open('', '_blank'); win.document.write(html); win.document.close();
  }
  window.openQuoteForVehicle = function(id) {
    const vehicle = findVehicle(id); if (!vehicle) return alert('Véhicule introuvable.');
    document.getElementById('quote-modal')?.remove();
    document.body.insertAdjacentHTML('beforeend', `<div id="quote-modal" class="admin-modal-backdrop"><div class="admin-modal" role="dialog" aria-modal="true"><h2>Demander un devis</h2><p><strong>Véhicule :</strong> ${esc(vehicle.name || vehicle.nom)}<br><span id="quote-price-note">Choisissez la zone.</span></p><form id="quote-form"><div class="form-grid"><div class="field"><label>Date de départ *</label><input id="quote-start-date" type="date" required></div><div class="field"><label>Date de retour *</label><input id="quote-end-date" type="date" required></div><div class="field"><label>Heure de départ *</label><input id="quote-start-time" type="time" value="07:00" required></div><div class="field"><label>Heure de retour *</label><input id="quote-end-time" type="time" value="18:00" required></div><div class="field"><label>Nom *</label><input id="quote-name" required></div><div class="field"><label>Prénom</label><input id="quote-first-name"></div><div class="field"><label>Numéro WhatsApp *</label><input id="quote-whatsapp" required placeholder="034 91 207 26"></div><div class="field full"><label>Adresse *</label><input id="quote-address" required></div><div class="field full"><label>Zone souhaitée *</label><select id="quote-zone"><option value="city">Tana et environs</option><option value="under_150">Province jusqu’à 150 km de Tana</option><option value="over_150">Province au-delà de 150 km de Tana</option></select></div></div><p id="quote-total" class="booking-result"></p><div class="modal-actions"><button type="button" class="btn outline" id="quote-close">Annuler</button><button class="btn primary">Générer le devis</button></div></form></div></div>`);
    const modal = document.getElementById('quote-modal'), form = document.getElementById('quote-form');
    const refresh = () => { const zone = document.getElementById('quote-zone').value, rate = rateFor(vehicle, zone), start = document.getElementById('quote-start-date').value, end = document.getElementById('quote-end-date').value, days = start && end ? Math.max(1, Math.ceil((new Date(`${end}T18:00`) - new Date(`${start}T07:00`)) / 86400000)) : 0; const unavailable = zone !== 'city' && vehicle[`province_${zone}_mode`] === 'unavailable'; document.getElementById('quote-price-note').textContent = `${zoneLabel(zone)} — ${unavailable ? 'Non disponible' : rate ? `${formatMGA(rate)} / jour` : 'Sur devis'}`; document.getElementById('quote-total').textContent = days ? (unavailable ? 'Cette zone n’est pas disponible.' : rate ? `Total estimatif : ${formatMGA(rate * days)} (${days} jour(s))` : 'Total : Sur devis') : ''; return {zone,rate,days,unavailable}; };
    ['quote-start-date','quote-end-date','quote-zone'].forEach(id2 => document.getElementById(id2).addEventListener('input', refresh));
    document.getElementById('quote-close').onclick = () => modal.remove(); refresh();
    form.onsubmit = async event => { event.preventDefault(); const q = refresh(); if (q.unavailable) return alert('Cette zone n’est pas disponible pour ce véhicule.'); const start = document.getElementById('quote-start-date').value, end = document.getElementById('quote-end-date').value; if (!q.days || new Date(`${end}T18:00`) <= new Date(`${start}T07:00`)) return alert('Vérifiez les dates du devis.'); const payload = {vehicle_id:vehicle.id,start_at:new Date(`${start}T${document.getElementById('quote-start-time').value}`).toISOString(),end_at:new Date(`${end}T${document.getElementById('quote-end-time').value}`).toISOString(),customer_name:document.getElementById('quote-name').value.trim(),customer_first_name:document.getElementById('quote-first-name').value.trim(),whatsapp_phone:document.getElementById('quote-whatsapp').value.trim(),customer_address:document.getElementById('quote-address').value.trim(),zone:q.zone,daily_rate:q.rate,days:q.days,total_amount:q.rate ? q.rate * q.days : null}; const result = await window.rentCarSupabase.rpc('create_public_quote', {p_payload:payload}); if (result.error) return alert(result.error.message); const row = Array.isArray(result.data) ? result.data[0] : result.data; if (!row) return alert('Le devis n’a pas pu être enregistré.'); printQuote({...payload,reference:row.reference,vehicle}); const target = String(siteConfig.footer.whatsapp || siteConfig.footer.telephone || '').replace(/\D/g, ''); window.open(`https://wa.me/${target}?text=${encodeURIComponent(`Rent Car Service — Demande de devis ${row.reference}. Client : ${payload.customer_name}.`)}`, '_blank'); modal.remove(); };
  };
})();
