(() => {
  const db=window.rentCarSupabase, $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const labels={new:'Brouillon',contacted:'Contactée',accepted:'Publié',rejected:'Refusée',archived:'Archivée'};
  const val=id=>$(id)?.value.trim()||null;
  async function loadVehicleSales(){const target=$('sales-table');if(!target)return;const {data,error}=await db.from('vehicle_sales').select('*').order('created_at',{ascending:false});if(error){target.innerHTML=`<div class="notice">Impossible de charger les annonces : ${esc(error.message)}</div>`;return;}target.innerHTML=(data||[]).map(s=>{const photos=Object.values(s.photo_urls||{}).filter(Boolean).map(url=>`<img class="sale-admin-thumb" src="${esc(url)}" alt="Photo voiture">`).join('');return `<div class="card" style="margin:10px 0"><div class="section-head"><div><strong>${esc(s.make)} ${esc(s.model)}</strong> ${s.year?`(${s.year})`:''}<br><small>${esc(s.seller_name)} · ${esc(s.seller_phone)}</small></div><select class="sale-status-select" onchange="window.updateVehicleSale('${s.id}',this.value)">${Object.entries(labels).map(([key,label])=>`<option value="${key}" ${s.status===key?'selected':''}>${label}</option>`).join('')}</select></div><div>${photos||'<span class="muted">Aucune photo</span>'}</div><p>${esc(s.description||'')}<br><small>${s.mileage_km?Number(s.mileage_km).toLocaleString('fr-FR')+' km':'—'} · ${s.asking_price?Number(s.asking_price).toLocaleString('fr-FR')+' Ar':'Prix à définir'} · ${esc(s.transmission||'')} · ${esc(s.fuel||'')}</small></p></div>`;}).join('')||'<div class="empty">Aucune annonce.</div>';}
  async function updateVehicleSale(id,status){const {error}=await db.from('vehicle_sales').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message);else loadVehicleSales();}
  function resetForm(){const form=$('admin-sale-form');form.reset();$('admin-sale-id').value='';form.classList.toggle('hidden');}
  async function saveSale(event){event.preventDefault();const form=event.target,button=form.querySelector('button[type="submit"]');button.disabled=true;try{const id=val('admin-sale-id');const payload={seller_name:val('admin-sale-seller'),seller_phone:val('admin-sale-phone'),seller_email:val('admin-sale-email'),seller_address:val('admin-sale-address'),make:val('admin-sale-make'),model:val('admin-sale-model'),year:Number(val('admin-sale-year'))||null,asking_price:Number(val('admin-sale-price'))||null,mileage_km:Number(val('admin-sale-mileage'))||null,description:val('admin-sale-description'),repairs_needed:val('admin-sale-repairs'),transmission:val('admin-sale-transmission'),fuel:val('admin-sale-fuel'),seats:Number(val('admin-sale-seats'))||null,status:val('admin-sale-status'),registration_card_status:val('admin-sale-registration'),insurance_status:val('admin-sale-insurance'),inspection_status:val('admin-sale-inspection'),pink_card_status:val('admin-sale-pink'),model_1_status:val('admin-sale-model1'),updated_at:new Date().toISOString()};const result=id?await db.from('vehicle_sales').update(payload).eq('id',id).select('id').single():await db.from('vehicle_sales').insert(payload).select('id').single();if(result.error)throw new Error(result.error.message);const files=Array.from($('admin-sale-photos').files||[]).slice(0,6),urls={};for(const file of files){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'-'),path=`${result.data.id}/${Date.now()}-${safe}`,upload=await db.storage.from('vehicle-sales').upload(path,file,{upsert:false,contentType:file.type});if(upload.error)throw new Error(upload.error.message);urls[file.name]=db.storage.from('vehicle-sales').getPublicUrl(path).data.publicUrl;}if(Object.keys(urls).length)await db.from('vehicle_sales').update({photo_urls:urls}).eq('id',result.data.id);form.reset();$('admin-sale-id').value='';form.classList.add('hidden');await loadVehicleSales();}catch(error){alert(`Annonce non enregistrée : ${error.message}`)}finally{button.disabled=false;}}
  window.loadVehicleSales=loadVehicleSales;window.updateVehicleSale=updateVehicleSale;document.addEventListener('DOMContentLoaded',()=>{$('sale-add')?.addEventListener('click',resetForm);$('admin-sale-form')?.addEventListener('submit',saveSale);setTimeout(loadVehicleSales,500);});
})();
